import * as React from "react";
import { cn } from "../cn.ts";
import { GLYPH_VIEWBOX, GLYPH_G, WORDMARK_D, WORDMARK_WIDTH, WORDMARK_CAP } from "./logo-paths.ts";

/**
 * The Sluice brand (Overhaul R1). The mark is the real traced glyph (a sluice gate on a flow line
 * with a settlement pulse); the wordmark is Michroma, wide-tracked — both inline currentColor
 * paths, so theming is instant with zero flash and the logo stays crisp at any size.
 * Assets for external use live in /public/brand (generated by scripts/build-brand.mjs).
 */

const [GX, GY, GW, GH] = GLYPH_VIEWBOX.split(" ").map(Number) as [number, number, number, number];

export function LogoMark({ className }: { className?: string }) {
  return (
    <svg
      viewBox={GLYPH_VIEWBOX}
      role="img"
      aria-label="Sluice"
      className={cn("h-6 w-auto text-hi", className)}
      dangerouslySetInnerHTML={{ __html: GLYPH_G }}
    />
  );
}

export function Logo({
  withWordmark = true,
  className,
}: {
  withWordmark?: boolean;
  className?: string;
}) {
  if (!withWordmark) return <LogoMark className={className} />;
  // Lockup geometry mirrors the generated logo-full assets: wordmark cap-height = 42% of glyph
  // height, baseline on the glyph's optical center line.
  const cap = 0.42 * GH;
  const scale = cap / WORDMARK_CAP;
  const gap = 0.42 * GH;
  const wordW = WORDMARK_WIDTH * scale;
  const W = GW + gap + wordW;
  const baseline = GY + GH / 2 + cap / 2;
  return (
    <svg
      viewBox={`${GX} ${GY} ${W} ${GH}`}
      role="img"
      aria-label="Sluice"
      className={cn("h-7 w-auto text-hi", className)}
    >
      <g dangerouslySetInnerHTML={{ __html: GLYPH_G }} />
      <g transform={`translate(${GX + GW + gap}, ${baseline}) scale(${scale})`}>
        <path d={WORDMARK_D} fill="currentColor" />
      </g>
    </svg>
  );
}
